-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 10:22:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horello
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horello
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horello` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `horello` ;

-- -----------------------------------------------------
-- Table `horello`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`user` (
  `uid` INT NOT NULL AUTO_INCREMENT,
  `uemail` VARCHAR(50) NULL,
  `upassword` VARCHAR(12) NULL,
  `uname` VARCHAR(12) NULL,
  `usex` VARCHAR(2) NULL,
  PRIMARY KEY (`uid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`project` (
  `pid` INT NOT NULL AUTO_INCREMENT,
  `pname` VARCHAR(30) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `manager_id` INT NOT NULL,
  PRIMARY KEY (`pid`),
  INDEX `fk_project_user1_idx` (`manager_id` ASC),
  CONSTRAINT `fk_project_user1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `horello`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`task` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `tname` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `project_pid` INT NOT NULL,
  PRIMARY KEY (`tid`),
  INDEX `fk_task_project1_idx` (`project_pid` ASC),
  CONSTRAINT `fk_task_project1`
    FOREIGN KEY (`project_pid`)
    REFERENCES `horello`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`chatroom` (
  `crid` INT NOT NULL AUTO_INCREMENT,
  `crname` VARCHAR(45) NULL,
  `project_pid` INT NOT NULL,
  PRIMARY KEY (`crid`),
  INDEX `fk_chatroom_project1_idx` (`project_pid` ASC),
  CONSTRAINT `fk_chatroom_project1`
    FOREIGN KEY (`project_pid`)
    REFERENCES `horello`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`chat` (
  `chid` INT NOT NULL,
  `chcontent` VARCHAR(50) NULL,
  `chatroom_crid` INT NOT NULL,
  `user_uid` INT NOT NULL,
  PRIMARY KEY (`chid`),
  INDEX `fk_chat_chatroom1_idx` (`chatroom_crid` ASC),
  INDEX `fk_chat_user1_idx` (`user_uid` ASC),
  CONSTRAINT `fk_chat_chatroom1`
    FOREIGN KEY (`chatroom_crid`)
    REFERENCES `horello`.`chatroom` (`crid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chat_user1`
    FOREIGN KEY (`user_uid`)
    REFERENCES `horello`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`file` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(50) NULL,
  `fpath` VARCHAR(50) NULL,
  `furl` VARCHAR(50) NULL,
  `project_pid` INT NOT NULL,
  PRIMARY KEY (`fid`),
  INDEX `fk_file_project_idx` (`project_pid` ASC),
  CONSTRAINT `fk_file_project`
    FOREIGN KEY (`project_pid`)
    REFERENCES `horello`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`user_in_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`user_in_project` (
  `uid` INT NOT NULL,
  `pid` INT NOT NULL,
  PRIMARY KEY (`uid`, `pid`),
  INDEX `fk_user_has_project_project1_idx` (`pid` ASC),
  INDEX `fk_user_has_project_user1_idx` (`uid` ASC),
  CONSTRAINT `fk_user_has_project_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `horello`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_project_project1`
    FOREIGN KEY (`pid`)
    REFERENCES `horello`.`project` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horello`.`user_in_chatroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horello`.`user_in_chatroom` (
  `uid` INT NOT NULL,
  `crid` INT NOT NULL,
  PRIMARY KEY (`uid`, `crid`),
  INDEX `fk_user_has_chatroom_chatroom1_idx` (`crid` ASC),
  INDEX `fk_user_has_chatroom_user1_idx` (`uid` ASC),
  CONSTRAINT `fk_user_has_chatroom_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `horello`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_chatroom_chatroom1`
    FOREIGN KEY (`crid`)
    REFERENCES `horello`.`chatroom` (`crid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
